### ISSUE TITLE
HTML no longer converted

### ISSUE THREAD

**Issue by SoftCreatR** [nicklima/strapi-blog-frontend-next#12]
Looks like the changes [here](https://github.com/nicklima/strapi-blog-frontend-next/commit/23d9b58419117c7fcc516a5f1fe7589fb059f23e#diff-e1461c0d675cf91b947fbfdc86c4e0c7272c418e14748b0d90c295d208f8fc9f) broke HTML served by Strapi, so Iframes for example (e.g. [here](https://strapi-blog-frontend-next.vercel.app/article/strapi-v4-is-here-check-out-what-has-changed-in-the-cms)) are no longer working as expected.

**Comment by nicklima** [comment]
Thanks for all your help and contributions @SoftCreatR.
I'm glad to have someone helping to improve this project 👊
