### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by SoftCreatR** [nicklima/strapi-blog-frontend-next#23]
Would be nice, if pagination would be added on all pages (even a next and previous link on the articles themselves).

Strapi supports pagination out of the box.

**Comment by nicklima** [comment]
Great idea. I will publish some posts on Strapi CMS later to help in this task.

**Comment by SoftCreatR** [comment]
Maybe this gives you an idea of how to do it: https://github.com/ivandoric/Making-Websites-With-Next.js-And-Strapi/commit/e0fa0ce7b933db591aa8a7e7a8ae0167fc3518af (Video: https://www.youtube.com/watch?v=ZG8VBfBDQZQ)

Alternatively, infinite scroll is cooler? Check this out then: https://github.com/ivandoric/Making-Websites-With-Next.js-And-Strapi/commit/057b49eea5ae43f06913bfa86ed89b26ca8d6d5e (Video: https://www.youtube.com/watch?v=VHf2EM38Ikg)
