### ISSUE TITLE
Images are not properly optimized

### ISSUE THREAD

**Issue by SoftCreatR** [nicklima/strapi-blog-frontend-next#6]
See https://pagespeed.web.dev/report?url=https%3A%2F%2Fstrapi-blog-frontend-next.vercel.app%2F

This doesn't seem to be a problem with Vercel and/or Cloudinary, but with your implementation. However, it "could" also be a problem with next/image.

Maybe, this is something you want to take a look at?

**Comment by nicklima** [comment]
Thanks for the tip @SoftCreatR. 
In fact it's something that I really want to take a deep look. I will keep your issue opened to motivate me to find out one solution.

**Comment by SoftCreatR** [comment]
This is more a bug, than an enhancement 😏 However, if you can figure this out, I have one or two additional optimizations.

**Comment by nicklima** [comment]
> This is more a bug, than an enhancement 😏 However, if you can figure this out, I have one or two additional optimizations.

Hello @SoftCreatR, I think that we can go further with the optimization. What are these ideas you were thinking of for the project? 🤔😄 

I had done some fixes in #15. Let's move this conversation to that issue.

**Comment by SoftCreatR** [comment]
Well, the Blurhash thing was one of the ideas, I had 😸 But I already answered on the other issue.

**Comment by nicklima** [comment]
@SoftCreatR Let's keep the talk there. I also answered there and reopened the issue.
